# Generated by Django 4.0.5 on 2022-06-01 22:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codpost', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('asiento', models.CharField(max_length=3)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bajaEn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bajaEn_Lugar', to='combi.lugar')),
                ('subeEn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subeEn_Lugar', to='combi.lugar')),
            ],
        ),
    ]
